apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webgame-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YashPimple/Project-4
    targetRevision: HEAD
    path: Manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: web-game

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
